<?
$PERM["/"]["2"]="D";
$PERM["/"]["G12"]="X";
$PERM["/"]["G11"]="R";
$PERM["/"]["*"]="D";
$PERM["/"]["G2"]="D";
$PERM["/"]["G21"]="R";
$PERM["telephony"]["U97"]="X";
$PERM["crm"]["G31"]="R";
$PERM["company"]["G8"]="W";
$PERM["marketplace"]["U156"]="X";
$PERM["marketplace"]["G11"]="D";
$PERM["pub"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["upload"]["20"]="T_8";
$PERM["upload"]["13"]="T_8";
$PERM["upload"]["*"]="R";
$PERM["about"]["G8"]="W";
$PERM["about"]["G10"]="W";
$PERM["extranet"]["11"]="T_8";
$PERM["extranet"]["15"]="T_10";
$PERM["extranet"]["14"]="T_8";
$PERM["extranet"]["13"]="T_8";
$PERM["extranet"]["*"]="D";
?>