<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Сотрудники");
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:socialnetwork_user", 
	".default", 
	array(
		"ITEM_DETAIL_COUNT" => "32",
		"ITEM_MAIN_COUNT" => "6",
		"DATE_TIME_FORMAT" => "d.m.Y H:i:s",
		"NAME_TEMPLATE" => "#LAST_NAME# #NAME# #SECOND_NAME#",
		"SHOW_LOGIN" => "Y",
		"CAN_OWNER_EDIT_DESKTOP" => "N",
		"GROUP_USE_KEYWORDS" => "Y",
		"GROUP_THUMBNAIL_SIZE" => "",
		"LOG_THUMBNAIL_SIZE" => "",
		"LOG_COMMENT_THUMBNAIL_SIZE" => "",
		"LOG_NEW_TEMPLATE" => "Y",
		"LOG_AUTH" => "N",
		"SM_THEME" => "grey",
		"USE_MAIN_MENU" => "N",
		"SHOW_RATING" => "",
		"RATING_ID" => array(
		),
		"RATING_TYPE" => "",
		"PATH_TO_GROUP" => "/workgroups/group/#group_id#/",
		"PATH_TO_GROUP_SUBSCRIBE" => "/workgroups/group/#group_id#/subscribe/",
		"PATH_TO_GROUP_SEARCH" => "/workgroups/group/search/",
		"PATH_TO_SEARCH_EXTERNAL" => "/company/index.php",
		"PATH_TO_CONPANY_DEPARTMENT" => "/company/structure.php?set_filter_structure=Y&structure_UF_DEPARTMENT=#ID#",
		"PATH_TO_GROUP_TASKS" => "/workgroups/group/#group_id#/tasks/",
		"PATH_TO_GROUP_TASKS_TASK" => "/workgroups/group/#group_id#/tasks/task/#action#/#task_id#/",
		"PATH_TO_GROUP_TASKS_VIEW" => "/workgroups/group/#group_id#/tasks/view/#action#/#view_id#/",
		"PATH_TO_GROUP_TASKS_REPORT" => "",
		"ALLOW_GROUP_CREATE_REDIRECT_REQUEST" => "Y",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "/company/personal/",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600",
		"CACHE_TIME_LONG" => "604800",
		"PATH_TO_SMILE" => "/bitrix/images/socialnetwork/smile/",
		"PATH_TO_BLOG_SMILE" => "/bitrix/images/blog/smile/",
		"PATH_TO_FORUM_SMILE" => "/bitrix/images/forum/smile/",
		"SONET_PATH_TO_FORUM_ICON" => "/bitrix/images/forum/icon/",
		"SET_TITLE" => "Y",
		"SET_NAV_CHAIN" => "Y",
		"USER_FIELDS_MAIN" => array(
			0 => "WORK_POSITION",
		),
		"USER_PROPERTY_MAIN" => array(
			0 => "UF_DEPARTMENT",
			1 => "UF_PHONE_INNER",
		),
		"USER_FIELDS_CONTACT" => array(
			0 => "EMAIL",
			1 => "PERSONAL_MOBILE",
			2 => "WORK_PHONE",
		),
		"USER_PROPERTY_CONTACT" => array(
			0 => "UF_PHONE_INNER",
			1 => "UF_SKYPE",
		),
		"USER_FIELDS_PERSONAL" => array(
			0 => "PERSONAL_GENDER",
		),
		"USER_PROPERTY_PERSONAL" => array(
		),
		"EDITABLE_FIELDS" => array(
			0 => "NAME",
			1 => "SECOND_NAME",
			2 => "LAST_NAME",
			3 => "EMAIL",
			4 => "TIME_ZONE",
			5 => "PERSONAL_BIRTHDAY",
			6 => "PERSONAL_ICQ",
			7 => "PERSONAL_GENDER",
			8 => "PERSONAL_PHOTO",
			9 => "PERSONAL_MOBILE",
		),
		"SHOW_YEAR" => "M",
		"USER_FIELDS_SEARCH_SIMPLE" => array(
			0 => "PERSONAL_GENDER",
			1 => "PERSONAL_CITY",
		),
		"USER_PROPERTIES_SEARCH_SIMPLE" => array(
		),
		"USER_FIELDS_SEARCH_ADV" => array(
			0 => "PERSONAL_GENDER",
			1 => "PERSONAL_COUNTRY",
			2 => "PERSONAL_CITY",
		),
		"USER_PROPERTIES_SEARCH_ADV" => array(
		),
		"SONET_USER_FIELDS_LIST" => array(
			0 => "PERSONAL_BIRTHDAY",
			1 => "PERSONAL_GENDER",
			2 => "PERSONAL_CITY",
		),
		"SONET_USER_PROPERTY_LIST" => array(
		),
		"SONET_USER_FIELDS_SEARCHABLE" => array(
		),
		"SONET_USER_PROPERTY_SEARCHABLE" => array(
		),
		"ALLOW_RATING_SORT" => "N",
		"CALENDAR_ALLOW_SUPERPOSE" => "Y",
		"CALENDAR_ALLOW_RES_MEETING" => "Y",
		"TASK_IBLOCK_TYPE" => "services",
		"TASK_IBLOCK_ID" => "24",
		"TASKS_FIELDS_SHOW" => array(
			0 => "ID",
			1 => "NAME",
			2 => "MODIFIED_BY",
			3 => "DATE_CREATE",
			4 => "CREATED_BY",
			5 => "DATE_ACTIVE_FROM",
			6 => "DATE_ACTIVE_TO",
			7 => "IBLOCK_SECTION",
			8 => "DETAIL_TEXT",
		),
		"TASK_FORUM_ID" => "8",
		"FILES_USER_IBLOCK_TYPE" => "library",
		"FILES_USER_IBLOCK_ID" => "15",
		"FILES_AUTO_PUBLISH" => "N",
		"FILES_USE_AUTH" => "Y",
		"FILE_NAME_FILE_PROPERTY" => "FILE",
		"FILES_UPLOAD_MAX_FILESIZE" => "1024",
		"FILES_UPLOAD_MAX_FILE" => "4",
		"FILES_USE_COMMENTS" => "Y",
		"FILES_FORUM_ID" => "1",
		"FILES_USE_CAPTCHA" => "Y",
		"BLOG_GROUP_ID" => "1",
		"ALLOW_POST_MOVE" => "N",
		"PATH_TO_GROUP_POST" => "/workgroups/group/#group_id#/blog/#post_id#/",
		"BLOG_IMAGE_MAX_WIDTH" => "800",
		"BLOG_IMAGE_MAX_HEIGHT" => "800",
		"BLOG_COMMENT_AJAX_POST" => "Y",
		"BLOG_COMMENT_ALLOW_IMAGE_UPLOAD" => "A",
		"BLOG_SHOW_SPAM" => "N",
		"BLOG_NO_URL_IN_COMMENTS" => "",
		"BLOG_NO_URL_IN_COMMENTS_AUTHORITY" => "",
		"BLOG_ALLOW_POST_CODE" => "Y",
		"BLOG_USE_GOOGLE_CODE" => "Y",
		"BLOG_USE_CUT" => "N",
		"FORUM_ID" => "3",
		"FORUM_THEME" => "blue",
		"USER_FIELDS_FORUM" => array(
			0 => "UF_FORUM_MESSAGE_DOC",
		),
		"SHOW_VOTE" => "N",
		"FORUM_AJAX_POST" => "N",
		"PHOTO_USER_IBLOCK_TYPE" => "photos",
		"PHOTO_USER_IBLOCK_ID" => "20",
		"PHOTO_MODERATION" => "N",
		"PHOTO_SECTION_PAGE_ELEMENTS" => "15",
		"PHOTO_ELEMENTS_PAGE_ELEMENTS" => "50",
		"PHOTO_ALBUM_PHOTO_THUMBS_SIZE" => "150",
		"PHOTO_THUMBNAIL_SIZE" => "100",
		"PHOTO_ORIGINAL_SIZE" => "1280",
		"PHOTO_UPLOADER_TYPE" => "flash",
		"PHOTO_WATERMARK_MIN_PICTURE_SIZE" => "400",
		"PHOTO_PATH_TO_FONT" => "",
		"PHOTO_SHOW_WATERMARK" => "Y",
		"PHOTO_WATERMARK_RULES" => "USER",
		"PHOTO_UPLOAD_MAX_FILESIZE" => "64",
		"PHOTO_USE_RATING" => "Y",
		"PHOTO_MAX_VOTE" => "5",
		"PHOTO_VOTE_NAMES" => array(
			0 => "1",
			1 => "2",
			2 => "3",
			3 => "4",
			4 => "5",
			5 => "",
		),
		"PHOTO_DISPLAY_AS_RATING" => "vote_avg",
		"PHOTO_USE_COMMENTS" => "Y",
		"PHOTO_COMMENTS_TYPE" => "forum",
		"PHOTO_FORUM_ID" => "2",
		"PHOTO_USE_CAPTCHA" => "N",
		"PATH_TO_GROUP_PHOTO" => "/workgroups/group/#group_id#/photo/",
		"PATH_TO_GROUP_PHOTO_SECTION" => "/workgroups/group/#group_id#/photo/album/#section_id#/",
		"PATH_TO_GROUP_PHOTO_ELEMENT" => "/workgroups/group/#group_id#/photo/#section_id#/#element_id#/",
		"LOG_PHOTO_COUNT" => "6",
		"LOG_PHOTO_THUMBNAIL_SIZE" => "48",
		"SEARCH_DEFAULT_SORT" => "rank",
		"SEARCH_PAGE_RESULT_COUNT" => "10",
		"SEARCH_TAGS_PAGE_ELEMENTS" => "100",
		"SEARCH_TAGS_PERIOD" => "",
		"SEARCH_TAGS_FONT_MAX" => "50",
		"SEARCH_TAGS_FONT_MIN" => "10",
		"SEARCH_TAGS_COLOR_NEW" => "3E74E6",
		"SEARCH_TAGS_COLOR_OLD" => "C0C0C0",
		"SEARCH_FILTER_NAME" => "sonet_search_filter",
		"SEARCH_FILTER_DATE_NAME" => "sonet_search_filter_date",
		"COMPONENT_TEMPLATE" => ".default",
		"BLOG_COMMENT_ALLOW_VIDEO" => "Y",
		"SEARCH_RESTART" => "N",
		"SEARCH_USE_LANGUAGE_GUESS" => "Y",
		"ALLOWALL_USER_PROFILE_FIELDS" => "N",
		"SEF_URL_TEMPLATES" => array(
			"index" => "index.php",
			"user_reindex" => "user_reindex.php",
			"user_content_search" => "user/#user_id#/search/",
			"user" => "user/#user_id#/",
			"user_friends" => "user/#user_id#/friends/",
			"user_friends_add" => "user/#user_id#/friends/add/",
			"user_friends_delete" => "user/#user_id#/friends/delete/",
			"user_groups" => "user/#user_id#/groups/",
			"user_groups_add" => "user/#user_id#/groups/add/",
			"group_create" => "user/#user_id#/groups/create/",
			"user_profile_edit" => "user/#user_id#/edit/",
			"user_settings_edit" => "user/#user_id#/settings/",
			"user_features" => "user/#user_id#/features/",
			"group_request_group_search" => "group/#user_id#/group_search/",
			"group_request_user" => "group/#group_id#/user/#user_id#/request/",
			"search" => "search.php",
			"message_form" => "messages/form/#user_id#/",
			"message_form_mess" => "messages/form/#user_id#/#message_id#/",
			"user_ban" => "messages/ban/",
			"messages_chat" => "messages/chat/#user_id#/",
			"messages_input" => "messages/input/",
			"messages_input_user" => "messages/input/#user_id#/",
			"messages_output" => "messages/output/",
			"messages_output_user" => "messages/output/#user_id#/",
			"messages_users" => "messages/",
			"messages_users_messages" => "messages/#user_id#/",
			"log" => "log/",
			"activity" => "user/#user_id#/activity/",
			"subscribe" => "subscribe/",
			"user_subscribe" => "user/#user_id#/subscribe/",
			"user_photo" => "user/#user_id#/photo/",
			"user_calendar" => "user/#user_id#/calendar/",
			"user_files" => "user/#user_id#/files/lib/#path#",
			"user_blog" => "user/#user_id#/blog/",
			"user_blog_post_edit" => "user/#user_id#/blog/edit/#post_id#/",
			"user_blog_rss" => "user/#user_id#/blog/rss/#type#/",
			"user_blog_draft" => "user/#user_id#/blog/draft/",
			"user_blog_post" => "user/#user_id#/blog/#post_id#/",
			"user_blog_moderation" => "user/#user_id#/blog/moderation/",
			"user_forum" => "user/#user_id#/forum/",
			"user_forum_topic_edit" => "user/#user_id#/forum/edit/#topic_id#/",
			"user_forum_topic" => "user/#user_id#/forum/#topic_id#/",
			"bizproc" => "bizproc/",
			"bizproc_edit" => "bizproc/#task_id#/",
			"video_call" => "video/#user_id#/",
			"processes" => "processes/",
			"user_tasks" => "user/#user_id#/tasks/",
			"user_tasks_task" => "user/#user_id#/tasks/task/#action#/#task_id#/",
			"user_tasks_view" => "user/#user_id#/tasks/view/#action#/#view_id#/",
			"user_tasks_departments_overview" => "user/#user_id#/tasks/departments/",
			"user_tasks_projects_overview" => "user/#user_id#/tasks/projects/",
			"user_tasks_report" => "user/#user_id#/tasks/report/",
			"user_tasks_templates" => "user/#user_id#/tasks/templates/",
			"user_templates_template" => "user/#user_id#/tasks/templates/template/#action#/#template_id#/",
		)
	),
	false
);?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>